/**
 * auth-page/auth.js — Supabase Authentication Logic
 * 
 * Handles:
 * - Google Sign-In via OAuth redirect
 * - Email/Password sign-in and sign-up
 * - Password reset
 * - Sends auth result back to the Chrome extension via chrome.runtime.sendMessage
 */

(function () {

    // Config is loaded from config.js (generated by setup-env.js)
    const CONFIG = window.AUTH_PAGE_CONFIG || {};

    // Initialize Supabase client
    const supabaseClient = supabase.createClient(CONFIG.SUPABASE_URL, CONFIG.SUPABASE_ANON_KEY);

    // ========================================================================
    // VIEW MANAGEMENT
    // ========================================================================

    const views = {
        signin: document.getElementById('view-signin'),
        signup: document.getElementById('view-signup'),
        forgot: document.getElementById('view-forgot'),
        success: document.getElementById('view-success')
    };

    function showView(name) {
        Object.values(views).forEach(v => v.classList.remove('active'));
        if (views[name]) views[name].classList.add('active');
    }

    // Navigation links
    document.getElementById('link-signup')?.addEventListener('click', () => showView('signup'));
    document.getElementById('link-signin')?.addEventListener('click', () => showView('signin'));
    document.getElementById('link-forgot')?.addEventListener('click', () => showView('forgot'));
    document.getElementById('link-back-signin')?.addEventListener('click', () => showView('signin'));

    // ========================================================================
    // ERROR HANDLING
    // ========================================================================

    function showError(message) {
        const el = document.getElementById('auth-error');
        const textEl = document.getElementById('auth-error-text');
        if (el && textEl) {
            textEl.textContent = message;
            el.classList.remove('hidden');
            setTimeout(() => el.classList.add('hidden'), 5000);
        }
    }

    document.getElementById('auth-error-close')?.addEventListener('click', () => {
        document.getElementById('auth-error')?.classList.add('hidden');
    });

    function supabaseErrorToMessage(err) {
        const msg = err?.message || err?.error_description || '';
        const map = {
            'Invalid login credentials': 'Invalid email or password.',
            'User already registered': 'An account with this email already exists.',
            'Password should be at least 6 characters': 'Password must be at least 6 characters.',
            'Unable to validate email address: invalid format': 'Please enter a valid email address.',
            'Email rate limit exceeded': 'Too many attempts. Please try again later.',
            'Signup requires a valid password': 'Please enter a valid password.'
        };
        return map[msg] || msg || 'An unexpected error occurred.';
    }

    // ========================================================================
    // CHECK FOR OAUTH REDIRECT (on page load)
    // ========================================================================

    // When returning from Google OAuth, Supabase appends tokens to the URL hash.
    // We must detect this and handle the session.
    (async function checkOAuthRedirect() {
        try {
            const { data, error } = await supabaseClient.auth.getSession();
            if (error) {
                console.warn('getSession error:', error);
                return;
            }
            if (data.session) {
                await handleAuthSuccess(data.session);
            }
        } catch (e) {
            console.warn('OAuth redirect check error:', e);
        }
    })();

    // Also listen for auth state changes (handles the hash fragment flow)
    supabaseClient.auth.onAuthStateChange(async (event, session) => {
        if (event === 'SIGNED_IN' && session) {
            await handleAuthSuccess(session);
        }
    });

    // ========================================================================
    // AUTH SUCCESS — Send token back to extension
    // ========================================================================

    let _authSuccessHandled = false; // Prevent duplicate sends

    async function handleAuthSuccess(session) {
        if (_authSuccessHandled) return;
        _authSuccessHandled = true;

        try {
            const user = session.user;

            const profile = {
                uid: user.id,
                email: user.email,
                name: user.user_metadata?.full_name || user.user_metadata?.name || '',
                avatarUrl: user.user_metadata?.avatar_url || user.user_metadata?.picture || '',
                provider: user.app_metadata?.provider || 'email'
            };

            const authData = {
                type: 'AUTH_SUCCESS',
                accessToken: session.access_token,
                refreshToken: session.refresh_token,
                profile
            };

            // Try to send to extension
            const extensionId = CONFIG.EXTENSION_ID;
            if (extensionId && chrome && chrome.runtime && chrome.runtime.sendMessage) {
                chrome.runtime.sendMessage(extensionId, authData, (response) => {
                    if (chrome.runtime.lastError) {
                        console.warn('Could not reach extension:', chrome.runtime.lastError.message);
                        showError('Could not connect to extension. Please make sure the extension is installed.');
                        _authSuccessHandled = false;
                        return;
                    }

                    if (response && response.syncStatus && response.syncStatus.status === 'NEEDS_MERGE') {
                        // Extension requested a merge decision
                        document.getElementById('merge-cloud-count').textContent = response.syncStatus.cloudCount || 0;
                        document.getElementById('merge-local-count').textContent = response.syncStatus.localCount || 0;
                        showView('merge');

                        // Wire up merge buttons
                        const mergeBothBtn = document.getElementById('btn-merge-both');
                        const mergeReplaceBtn = document.getElementById('btn-merge-replace');
                        const spinner = document.getElementById('merge-spinner');

                        const sendDecision = (choice) => {
                            mergeBothBtn.disabled = true;
                            mergeReplaceBtn.disabled = true;
                            spinner.classList.remove('hidden');

                            chrome.runtime.sendMessage(extensionId, { type: 'MERGE_DECISION', choice }, (res) => {
                                spinner.classList.add('hidden');
                                if (chrome.runtime.lastError || (res && !res.success)) {
                                    showError('Data sync failed: ' + (chrome.runtime.lastError?.message || res?.error));
                                } else {
                                    showView('success');
                                }
                            });
                        };

                        mergeBothBtn.onclick = () => sendDecision('merge');
                        mergeReplaceBtn.onclick = () => sendDecision('replace');

                    } else {
                        // Standard authentication success
                        showView('success');
                    }
                });
            } else {
                console.warn('chrome.runtime not available — running outside extension context');
                showView('success');
            }

        } catch (err) {
            console.error('handleAuthSuccess error:', err);
            showError('Sign-in succeeded but failed to connect to extension.');
            _authSuccessHandled = false;
        }
    }

    // ========================================================================
    // SOCIAL SIGN-IN
    // ========================================================================

    // Google
    document.getElementById('btn-google')?.addEventListener('click', async () => {
        const btn = document.getElementById('btn-google');
        btn.disabled = true;
        btn.classList.add('loading');
        try {
            const { error } = await supabaseClient.auth.signInWithOAuth({
                provider: 'google',
                options: {
                    redirectTo: window.location.origin + window.location.pathname
                }
            });
            if (error) throw error;
            // Page will redirect to Google, then back here. onAuthStateChange handles the rest.
        } catch (err) {
            console.error('Google sign-in error:', err);
            showError(supabaseErrorToMessage(err));
            btn.disabled = false;
            btn.classList.remove('loading');
        }
    });

    // GitHub
    document.getElementById('btn-github')?.addEventListener('click', async () => {
        const btn = document.getElementById('btn-github');
        btn.disabled = true;
        btn.classList.add('loading');
        try {
            const { error } = await supabaseClient.auth.signInWithOAuth({
                provider: 'github',
                options: {
                    redirectTo: window.location.origin + window.location.pathname
                }
            });
            if (error) throw error;
        } catch (err) {
            console.error('GitHub sign-in error:', err);
            showError(supabaseErrorToMessage(err));
            btn.disabled = false;
            btn.classList.remove('loading');
        }
    });

    // ========================================================================
    // EMAIL / PASSWORD
    // ========================================================================

    // Sign In
    document.getElementById('form-signin')?.addEventListener('submit', async (e) => {
        e.preventDefault();
        const email = document.getElementById('signin-email').value.trim();
        const password = document.getElementById('signin-password').value;
        const btn = e.target.querySelector('.auth-submit-btn');

        btn.disabled = true;
        btn.textContent = 'Signing in...';

        try {
            const { data, error } = await supabaseClient.auth.signInWithPassword({ email, password });
            if (error) throw error;
            await handleAuthSuccess(data.session);
        } catch (err) {
            showError(supabaseErrorToMessage(err));
        } finally {
            btn.disabled = false;
            btn.textContent = 'Sign In';
        }
    });

    // Sign Up
    document.getElementById('form-signup')?.addEventListener('submit', async (e) => {
        e.preventDefault();
        const name = document.getElementById('signup-name').value.trim();
        const email = document.getElementById('signup-email').value.trim();
        const password = document.getElementById('signup-password').value;
        const btn = e.target.querySelector('.auth-submit-btn');

        btn.disabled = true;
        btn.textContent = 'Creating account...';

        try {
            const { data, error } = await supabaseClient.auth.signUp({
                email,
                password,
                options: {
                    data: { full_name: name }
                }
            });
            if (error) throw error;

            if (data.session) {
                // Auto-confirmed (e.g. when email confirmation is disabled)
                await handleAuthSuccess(data.session);
            } else {
                // Email confirmation required
                showError('Check your email to confirm your account, then sign in.');
                showView('signin');
            }
        } catch (err) {
            showError(supabaseErrorToMessage(err));
        } finally {
            btn.disabled = false;
            btn.textContent = 'Create Account';
        }
    });

    // Forgot Password
    document.getElementById('form-forgot')?.addEventListener('submit', async (e) => {
        e.preventDefault();
        const email = document.getElementById('forgot-email').value.trim();
        const btn = e.target.querySelector('.auth-submit-btn');

        btn.disabled = true;
        btn.textContent = 'Sending...';

        try {
            const { error } = await supabaseClient.auth.resetPasswordForEmail(email, {
                redirectTo: window.location.origin + window.location.pathname
            });
            if (error) throw error;
            btn.textContent = '✓ Email Sent!';
            setTimeout(() => {
                btn.textContent = 'Send Reset Link';
                showView('signin');
            }, 3000);
        } catch (err) {
            showError(supabaseErrorToMessage(err));
            btn.textContent = 'Send Reset Link';
        } finally {
            btn.disabled = false;
        }
    });

})();
