// AUTO-GENERATED BY setup-env.js — Config for the hosted login page
window.AUTH_PAGE_CONFIG = {
    SUPABASE_URL: "https://xhzsoaamuityxjulhams.supabase.co",
    SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhoenNvYWFtdWl0eXhqdWxoYW1zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ0MzE3MDAsImV4cCI6MjA5MDAwNzcwMH0.Voa4CEZXFnehSoNMBBLr_rRjO6m_LhWWIh__NFGCdhk",
    EXTENSION_ID: "dnhikbnbnljdenedgkmadcjjflcbniop"
};
