// AUTO-GENERATED BY setup-env.js — Config for the hosted login page
window.AUTH_PAGE_CONFIG = {
    SUPABASE_URL: "https://hilvbolnvvpktjeyezsl.supabase.co",
    SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpbHZib2xudnZwa3RqZXllenNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ3MTM0MzksImV4cCI6MjA5MDI4OTQzOX0.5uGlw5RVY6slYyj65jMFh0WxSW9VcgFdzqJ8AqqnBc8",
    EXTENSION_ID: "dnhikbnbnljdenedgkmadcjjflcbniop"
};
