const fs = require('fs');
const path = require('path');

console.log('⚙️  Injecting environment variables...');

const envPath = path.join(__dirname, '.env');

if (!fs.existsSync(envPath)) {
    console.error('❌ Error: .env file not found!');
    console.log('💡 Tip: Copy .env.example to .env and fill in your credentials.');
    process.exit(1);
}

// 1. Parse .env file
const envContent = fs.readFileSync(envPath, 'utf8');
const env = {};
envContent.split('\n').forEach(line => {
    // Ignore comments and empty lines
    if (!line || line.startsWith('#')) return;
    
    const [key, ...rest] = line.split('=');
    if (key && rest.length > 0) {
        env[key.trim()] = rest.join('=').trim().replace(/^['"]|['"]$/g, '');
    }
});

// 2. Generate core/env.js for extension use
const adminEmails = env.ADMIN_EMAILS 
    ? env.ADMIN_EMAILS.split(',').map(e => e.trim()).filter(Boolean) 
    : [];

const envJsContent = `// AUTO-GENERATED BY setup-env.js - DO NOT EDIT MANUALLY
globalThis.ENV = {
    SUPABASE_URL: "${env.SUPABASE_URL || ''}",
    SUPABASE_ANON_KEY: "${env.SUPABASE_ANON_KEY || ''}",
    ADMIN_EMAILS: ${JSON.stringify(adminEmails)},
    AUTH_PAGE_URL: "${env.AUTH_PAGE_URL || ''}"
};
`;

const envJsPath = path.join(__dirname, 'core', 'env.js');
fs.writeFileSync(envJsPath, envJsContent);
console.log('✅ Generated core/env.js');

// 3. Generate auth-page/config.js for the hosted login page
const authConfigContent = `// AUTO-GENERATED BY setup-env.js — Config for the hosted login page
window.AUTH_PAGE_CONFIG = {
    SUPABASE_URL: "${env.SUPABASE_URL || ''}",
    SUPABASE_ANON_KEY: "${env.SUPABASE_ANON_KEY || ''}",
    EXTENSION_ID: "${env.EXTENSION_ID || 'YOUR_EXTENSION_ID'}"
};
`;

const authConfigDir = path.join(__dirname, 'auth-page');
if (!fs.existsSync(authConfigDir)) {
    fs.mkdirSync(authConfigDir, { recursive: true });
}
fs.writeFileSync(path.join(authConfigDir, 'config.js'), authConfigContent);
console.log('✅ Generated auth-page/config.js');

console.log('🚀 Setup complete!');
console.log('');
console.log('Next steps:');
console.log('  1. Deploy auth-page/ to your hosting provider (Vercel, Netlify, GitHub Pages)');
console.log('  2. Set the Site URL in Supabase Dashboard → Authentication → URL Configuration');
console.log('  3. Reload the extension in chrome://extensions/');
