/**
 * core/sync.js — Supabase Cloud Sync + User Registry + Premium
 * 
 * Web-Based Auth Flow:
 * - Opens a hosted login page for authentication
 * - Receives auth tokens via chrome.runtime.onMessageExternal
 * - Uses Supabase client for all database + storage operations
 * - Supports Google, GitHub, and Email/Password login
 * 
 * Data Structure in Supabase (Postgres):
 *   profiles               → user profile, premium, timestamps
 *   folders                → per-row folder storage
 *   notes                  → per-row note storage
 *   vault_data             → encrypted vault blob (JSONB)
 *   vault_keys             → EDEK, salt, validator
 *   user_settings           → settings JSONB
 *   tombstones             → deleted item UUIDs
 *   Storage: user-files/{uid}/  → uploaded blobs (images, PDFs, videos)
 */

const SyncService = (function () {

    // ========================================================================
    // CONFIGURATION — Loaded from core/env.js (generated by setup-env.js)
    // ========================================================================
    const ENV = globalThis.ENV || {};

    const SUPABASE_URL = ENV.SUPABASE_URL || '';
    const SUPABASE_ANON_KEY = ENV.SUPABASE_ANON_KEY || '';
    const ADMIN_EMAILS = ENV.ADMIN_EMAILS || [];
    const AUTH_PAGE_URL = ENV.AUTH_PAGE_URL || '';

    const SYNC_STATE_KEY = 'sync_state';
    const DEBOUNCE_MS = 3000;

    let _debounceTimer = null;
    let _syncInProgress = false;
    let _supabase = null;
    let _realtimeChannel = null;

    /**
     * Get or create the Supabase client singleton.
     */
    function _getSupabaseClient() {
        if (_supabase) return _supabase;

        if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
            console.error('[Sync] Supabase URL or Anon Key not configured.');
            return null;
        }

        // supabase global is from vendor/supabase.min.js (UMD)
        const createClient = globalThis.supabase?.createClient;
        if (!createClient) {
            console.error('[Sync] Supabase JS client not loaded. Check vendor/supabase.min.js');
            return null;
        }

        _supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
            auth: {
                persistSession: false, // We manage sessions in chrome.storage
                autoRefreshToken: false
            }
        });

        return _supabase;
    }

    // ========================================================================
    // AUTH — Web-Based Supabase Authentication
    // ========================================================================

    /**
     * Sign in — Opens the hosted login page in a new tab.
     * Auth result is received via chrome.runtime.onMessageExternal (handled in background.js).
     */
    async function signIn() {
        const loginUrl = `${AUTH_PAGE_URL}/index.html`;
        chrome.tabs.create({ url: loginUrl });
    }

    /**
     * Process the auth result received from the login page.
     * Called by background.js when it receives the external message.
     */
    async function handleAuthResult(authData) {
        try {
            const { accessToken, refreshToken, profile, vaultKeys } = authData;

            // Set the session on the Supabase client
            const sb = _getSupabaseClient();
            if (sb) {
                await sb.auth.setSession({
                    access_token: accessToken,
                    refresh_token: refreshToken
                });
            }

            // Save auth tokens
            const state = await _getSyncState();
            state.googleProfile = profile; // Keep field name for backward compat with UI code
            state.accessToken = accessToken;
            state.refreshToken = refreshToken;
            state.syncStatus = 'idle';
            state.tokenExpiresAt = Date.now() + (55 * 60 * 1000);
            await _setSyncState(state);

            // If vault keys were provided (new sign-up with master password),
            // store them and secure the vault with the encryption keys
            if (vaultKeys) {
                await new Promise((resolve) => {
                    chrome.storage.local.set({ pm_vault_keys: vaultKeys }, resolve);
                });

                // If there's an existing VaultService, secure the vault
                // (encrypts any existing plaintext data)
                if (globalThis.vaultService && typeof globalThis.vaultService.secureVault === 'function') {
                    // We need the master password to call secureVault properly,
                    // but we don't have it here. The vault keys are already derived.
                    // Instead, we store the keys directly and let the vault service
                    // detect them on next access via isSecured().
                    // The plaintext data will be encrypted on the next vault load.
                    console.log('[Sync] Vault keys stored. Vault will be secured on next access.');
                }
            }

            // Register/update user in Supabase
            await _registerUser(profile);

            // Trigger first sync with smart merge
            const syncStatus = await _firstSync();

            return { profile, syncStatus };
        } catch (err) {
            console.error('SyncService.handleAuthResult failed:', err);
            throw err;
        }
    }

    /**
     * Sign out — Clear all local data, settings, tokens, and IndexedDB.
     */
    async function signOut() {
        // Sign out from Supabase
        const sb = _getSupabaseClient();
        if (sb) {
            await sb.auth.signOut().catch(() => {});
        }

        // Unsubscribe from realtime
        _unsubscribeRealtime();

        // Wipe all chrome.storage.local
        await new Promise(resolve => chrome.storage.local.clear(resolve));

        // Wipe IndexedDB
        try {
            const db = await AppDB.initDB();
            const tx = db.transaction(['items', 'folders'], 'readwrite');
            tx.objectStore('items').clear();
            tx.objectStore('folders').clear();
            await new Promise((resolve) => {
                tx.oncomplete = resolve;
                tx.onerror = resolve;
            });
        } catch (e) {
            console.error('[Sync] Error wiping IndexedDB on logout:', e);
        }

        // Re-initialize a clean sync state
        await _setSyncState({
            lastSyncedAt: null,
            googleProfile: null,
            accessToken: null,
            refreshToken: null,
            isPremium: false,
            autoSync: true,
            syncStatus: 'idle',
            tokenExpiresAt: null
        });
        
        chrome.runtime.reload();
    }

    /**
     * Check if user is currently signed in.
     */
    async function isSignedIn() {
        const state = await _getSyncState();
        return !!(state.googleProfile && state.googleProfile.email && state.accessToken);
    }

    /**
     * Check if user has premium status.
     */
    async function isPremium() {
        const state = await _getSyncState();
        return !!state.isPremium;
    }

    /**
     * Get cached user profile or null.
     */
    async function getProfile() {
        const state = await _getSyncState();
        return state.googleProfile || null;
    }

    /**
     * Check if current user is an admin.
     */
    async function isAdmin() {
        const profile = await getProfile();
        return profile && ADMIN_EMAILS.includes(profile.email);
    }

    /**
     * Ensure the Supabase client has a valid session. Refreshes if needed.
     * Returns the authenticated Supabase client.
     */
    async function _getAuthenticatedClient() {
        const sb = _getSupabaseClient();
        if (!sb) throw new Error('Supabase client not initialized');

        const state = await _getSyncState();
        if (!state.accessToken || !state.refreshToken) {
            throw new Error('Not signed in');
        }

        // Check if token is still valid (with 5 min buffer)
        if (state.tokenExpiresAt && Date.now() < (state.tokenExpiresAt - 5 * 60 * 1000)) {
            // Token is still valid, ensure session is set
            await sb.auth.setSession({
                access_token: state.accessToken,
                refresh_token: state.refreshToken
            });
            return sb;
        }

        // Refresh the session
        const { data, error } = await sb.auth.setSession({
            access_token: state.accessToken,
            refresh_token: state.refreshToken
        });

        if (error || !data.session) {
            await signOut();
            throw new Error('Session expired. Please sign in again.');
        }

        // Update stored tokens
        state.accessToken = data.session.access_token;
        state.refreshToken = data.session.refresh_token;
        state.tokenExpiresAt = Date.now() + (55 * 60 * 1000);
        await _setSyncState(state);

        return sb;
    }

    // ========================================================================
    // PREMIUM — Toggle premium membership
    // ========================================================================

    async function setPremiumStatus(isPremiumFlag) {
        const sb = await _getAuthenticatedClient();
        const state = await _getSyncState();
        if (!state.googleProfile) throw new Error('Not signed in');

        const uid = state.googleProfile.uid;
        const { error } = await sb.from('profiles').update({
            is_premium: isPremiumFlag,
            premium_since: isPremiumFlag ? new Date().toISOString() : null
        }).eq('id', uid);

        if (error) throw error;

        state.isPremium = isPremiumFlag;
        await _setSyncState(state);
    }

    // ========================================================================
    // SYNC — Supabase Cloud Sync
    // ========================================================================

    /**
     * First-time sync with smart merge logic.
     */
    async function _firstSync() {
        const sb = await _getAuthenticatedClient();
        const state = await _getSyncState();
        const uid = state.googleProfile.uid;

        // Check cloud data
        const { data: cloudNotes } = await sb.from('notes').select('*').eq('user_id', uid);
        const { data: cloudFolders } = await sb.from('folders').select('*').eq('user_id', uid);
        const { data: cloudVault } = await sb.from('vault_data').select('*').eq('user_id', uid).maybeSingle();
        const { data: cloudSettings } = await sb.from('user_settings').select('*').eq('user_id', uid).maybeSingle();

        const hasCloudNotes = cloudNotes && cloudNotes.length > 0;
        const hasCloudFolders = cloudFolders && cloudFolders.length > 0;
        const hasCloudVault = !!(cloudVault && cloudVault.encrypted_vault && Object.keys(cloudVault.encrypted_vault).length > 0);
        const hasCloudSettings = !!(cloudSettings && cloudSettings.settings && Object.keys(cloudSettings.settings).length > 0);
        const hasCloudData = hasCloudNotes || hasCloudFolders || hasCloudVault || hasCloudSettings;

        // Check local data
        const localData = await exportLocalData();
        const hasLocalNotes = localData.items?.length > 0;
        const hasLocalFolders = localData.folders?.length > 0;
        const hasLocalVault = !!(localData.vault?.encrypted_vault || localData.vault?.data);
        const hasLocalData = hasLocalNotes || hasLocalFolders || hasLocalVault;

        if (!hasCloudData && hasLocalData) {
            console.log('[Sync] First sync: uploading local data to cloud');
            await _uploadAllToCloud(uid, localData);
            _subscribeRealtime(uid);
            return { status: 'DONE' };
        } else if (hasCloudData && !hasLocalData) {
            console.log('[Sync] First sync: downloading cloud data to local');
            await _downloadAllFromCloud(uid);
            _subscribeRealtime(uid);
            return { status: 'DONE' };
        } else if (hasCloudData && hasLocalData) {
            console.log('[Sync] First sync: both local and cloud data exist — prompting user');
            return {
                status: 'NEEDS_MERGE',
                cloudCount: (cloudNotes?.length || 0),
                localCount: localData.items?.length || 0
            };
        } else {
            console.log('[Sync] First sync: no data anywhere, nothing to sync');
            state.lastSyncedAt = new Date().toISOString();
            await _setSyncState(state);
            _subscribeRealtime(uid);
            return { status: 'DONE' };
        }
    }

    /**
     * Handle the user's merge prompt response.
     */
    async function handleMergeResponse(choice) {
        const sb = await _getAuthenticatedClient();
        const state = await _getSyncState();
        const uid = state.googleProfile.uid;

        if (choice === 'merge') {
            // Merge: combine local + cloud, deduplicate, upload merged
            const localData = await exportLocalData();
            const { data: cloudNotes } = await sb.from('notes').select('*').eq('user_id', uid);
            const { data: cloudFolders } = await sb.from('folders').select('*').eq('user_id', uid);
            const { data: tombstones } = await sb.from('tombstones').select('*').eq('user_id', uid);

            const mergedNotes = _mergeNotesData(localData, { items: cloudNotes || [], folders: cloudFolders || [] }, { items: tombstones || [] });
            await importNotesData(mergedNotes.data);

            // Re-export and upload
            const freshLocal = await exportLocalData();
            await _uploadAllToCloud(uid, freshLocal);
            await new Promise(res => chrome.storage.local.set({ unpushedLocalChanges: false }, res));
        } else {
            // Replace: download cloud data, overwrite local
            await _downloadAllFromCloud(uid);
            await new Promise(res => chrome.storage.local.set({ unpushedLocalChanges: false }, res));
        }

        const now = new Date().toISOString();
        state.lastSyncedAt = now;
        state.syncStatus = 'idle';
        await _setSyncState(state);

        _subscribeRealtime(uid);
    }

    /**
     * Record a deleted item/folder UUID as a tombstone.
     */
    async function _recordTombstone(uuid, version = null) {
        try {
            const sb = await _getAuthenticatedClient();
            const state = await _getSyncState();
            const uid = state.googleProfile?.uid;
            if (!uid) return;

            await sb.from('tombstones').upsert({
                user_id: uid,
                uuid: uuid,
                version: version || 999999,
                deleted_at: new Date().toISOString()
            }, { onConflict: 'user_id,uuid' });
        } catch (e) {
            console.warn('[Sync] Could not record tombstone:', e);
        }
    }

    /**
     * Master sync function: per-item sync with conflict resolution.
     */
    async function syncAll(retryCount = 0) {
        if (retryCount > 3) throw new Error('Sync failed after 3 retries');

        if (retryCount === 0) {
            if (_syncInProgress) return;
            _syncInProgress = true;
        }

        const state = await _getSyncState();
        state.syncStatus = 'syncing';
        await _setSyncState(state);

        try {
            const sb = await _getAuthenticatedClient();
            const uid = state.googleProfile.uid;

            // 1. Get local dirtiness flags
            const flagData = await new Promise(res => chrome.storage.local.get(['unpushedLocalChanges', 'unpushedVaultChanges'], res));
            let unpushedLocalChanges = !!flagData.unpushedLocalChanges;
            let unpushedVaultChanges = !!flagData.unpushedVaultChanges;

            // 2. Load Local Data
            let localData = await exportLocalData();

            // 3. Pull Cloud Data
            const { data: cloudNotes } = await sb.from('notes').select('*').eq('user_id', uid);
            const { data: cloudFolders } = await sb.from('folders').select('*').eq('user_id', uid);
            const { data: cloudVault } = await sb.from('vault_data').select('*').eq('user_id', uid).maybeSingle();
            const { data: cloudVaultKeys } = await sb.from('vault_keys').select('*').eq('user_id', uid).maybeSingle();
            const { data: cloudSettings } = await sb.from('user_settings').select('*').eq('user_id', uid).maybeSingle();
            const { data: tombstones } = await sb.from('tombstones').select('*').eq('user_id', uid);

            let needsPush = unpushedLocalChanges || unpushedVaultChanges;

            // 4. MERGE Notes & Folders
            const cloudData = { items: cloudNotes || [], folders: cloudFolders || [] };
            if (cloudData.items.length > 0 || cloudData.folders.length > 0) {
                const mergeResult = _mergeNotesData(localData, cloudData, { items: tombstones || [] });
                await importNotesData(mergeResult.data);
                await _applyTombstonesLocally({ items: tombstones || [] }, localData);

                if (mergeResult.localWon) {
                    needsPush = true;
                }
            } else {
                if (localData.items.length > 0 || localData.folders.length > 0) needsPush = true;
            }

            // 5. MERGE Vault Keys
            if (cloudVaultKeys && (!localData.vaultKeys || cloudVaultKeys.salt !== localData.vaultKeys.salt)) {
                await new Promise(r => chrome.storage.local.set({
                    pm_vault_keys: {
                        salt: cloudVaultKeys.salt,
                        edek: cloudVaultKeys.edek,
                        edek_iv: cloudVaultKeys.edek_iv,
                        validator: cloudVaultKeys.validator,
                        validator_iv: cloudVaultKeys.validator_iv
                    }
                }, r));
                needsPush = false;
                if (typeof window !== 'undefined' && window.vaultService) window.vaultService.lock();
            } else if (localData.vaultKeys && !cloudVaultKeys) {
                needsPush = true;
            }

            // 6. MERGE Vault Data
            if (cloudVault && cloudVault.encrypted_vault) {
                const cloudVaultPayload = cloudVault.encrypted_vault;
                if (typeof window !== 'undefined' && window.vaultService && window.vaultService.isUnlocked) {
                    const mergeResult = await window.vaultService.mergeCloudVault(cloudVaultPayload, { items: tombstones || [] });
                    if (mergeResult.localWon) needsPush = true;
                } else {
                    const localVer = localData.vault?.version || 1;
                    const cloudVer = cloudVault.version || 1;

                    if (cloudVer > localVer) {
                        await _importVaultData(cloudVaultPayload, cloudVault.version);
                    } else if (localVer > cloudVer) {
                        needsPush = true;
                    }
                }
            } else if (localData.vault) {
                needsPush = true;
            }

            // 7. MERGE Settings
            const localSettingsTime = new Date(localData._settingsUpdatedAt || 0).getTime();
            const cloudSettingsTime = new Date(cloudSettings?.updated_at || 0).getTime();
            if (cloudSettings && cloudSettingsTime > localSettingsTime) {
                await _importSettingsData(cloudSettings.settings, cloudSettings.updated_at);
            } else if (Object.keys(localData.settings).length > 0 && localSettingsTime > cloudSettingsTime) {
                needsPush = true;
            }

            // 8. PUSH PHASE — per-item upserts
            if (needsPush) {
                let finalDataToUpload = await exportLocalData();
                await _uploadAllToCloud(uid, finalDataToUpload);
                await new Promise(res => chrome.storage.local.set({ unpushedLocalChanges: false, unpushedVaultChanges: false }, res));
            }

            // 9. Update local sync state
            const now = new Date().toISOString();
            state.lastSyncedAt = now;
            state.syncStatus = 'idle';
            await _setSyncState(state);

            // Update user profile timestamp
            await sb.from('profiles').update({ last_synced_at: now }).eq('id', uid).catch(() => {});

            // Ensure realtime subscription is active
            _subscribeRealtime(uid);

        } catch (err) {
            console.error('SyncService.syncAll failed:', err);
            state.syncStatus = 'error';
            await _setSyncState(state);
        } finally {
            if (retryCount === 0) {
                _syncInProgress = false;
            }
        }
    }

    /**
     * Debounced auto-sync — call after data changes.
     */
    function triggerAutoSync() {
        if (_debounceTimer) clearTimeout(_debounceTimer);
        _debounceTimer = setTimeout(async () => {
            const state = await _getSyncState();
            if (state.autoSync && state.googleProfile) {
                syncAll();
            }
        }, DEBOUNCE_MS);
    }

    // ========================================================================
    // REALTIME — Supabase Realtime Subscriptions
    // ========================================================================

    function _subscribeRealtime(uid) {
        if (_realtimeChannel) return; // Already subscribed

        const sb = _getSupabaseClient();
        if (!sb) return;

        _realtimeChannel = sb
            .channel('sync-changes')
            .on('postgres_changes', {
                event: '*',
                schema: 'public',
                table: 'notes',
                filter: `user_id=eq.${uid}`
            }, (payload) => _handleRealtimeChange('notes', payload))
            .on('postgres_changes', {
                event: '*',
                schema: 'public',
                table: 'folders',
                filter: `user_id=eq.${uid}`
            }, (payload) => _handleRealtimeChange('folders', payload))
            .on('postgres_changes', {
                event: '*',
                schema: 'public',
                table: 'vault_data',
                filter: `user_id=eq.${uid}`
            }, (payload) => _handleRealtimeChange('vault_data', payload))
            .on('postgres_changes', {
                event: '*',
                schema: 'public',
                table: 'tombstones',
                filter: `user_id=eq.${uid}`
            }, (payload) => _handleRealtimeChange('tombstones', payload))
            .subscribe();
    }

    function _unsubscribeRealtime() {
        if (_realtimeChannel) {
            const sb = _getSupabaseClient();
            if (sb) sb.removeChannel(_realtimeChannel);
            _realtimeChannel = null;
        }
    }

    /**
     * Handle an inbound Realtime change from another device.
     */
    async function _handleRealtimeChange(table, payload) {
        console.log(`[Sync Realtime] ${table} ${payload.eventType}`, payload);

        try {
            if (table === 'notes') {
                if (payload.eventType === 'INSERT' || payload.eventType === 'UPDATE') {
                    const row = payload.new;
                    // Upsert into local IndexedDB
                    await importNotesData({
                        folders: [],
                        items: [{
                            uuid: row.uuid,
                            folderId: null, // Will be resolved by folder_uuid
                            folderUuid: row.folder_uuid,
                            type: row.type,
                            title: row.title,
                            content: row.content,
                            fileUrl: row.file_url,
                            fileMimeType: row.file_mime_type,
                            tags: row.tags,
                            version: row.version,
                            createdAt: row.created_at,
                            updatedAt: row.updated_at
                        }]
                    });
                } else if (payload.eventType === 'DELETE') {
                    const row = payload.old;
                    if (row.uuid) {
                        await _deleteLocalItemByUuid(row.uuid);
                    }
                }
            } else if (table === 'folders') {
                if (payload.eventType === 'INSERT' || payload.eventType === 'UPDATE') {
                    const row = payload.new;
                    await importNotesData({
                        folders: [{
                            uuid: row.uuid,
                            name: row.name,
                            pin: row.pin,
                            parentId: row.parent_id,
                            order: row.order,
                            version: row.version,
                            createdAt: row.created_at,
                            updatedAt: row.updated_at
                        }],
                        items: []
                    });
                } else if (payload.eventType === 'DELETE') {
                    const row = payload.old;
                    if (row.uuid) {
                        await _deleteLocalFolderByUuid(row.uuid);
                    }
                }
            } else if (table === 'vault_data') {
                // Re-sync vault on change
                syncAll();
            } else if (table === 'tombstones') {
                if (payload.eventType === 'INSERT') {
                    const row = payload.new;
                    await _deleteLocalItemByUuid(row.uuid);
                    await _deleteLocalFolderByUuid(row.uuid);
                }
            }

            // Notify UI to refresh
            if (typeof chrome !== 'undefined' && chrome.runtime) {
                chrome.runtime.sendMessage({ action: 'sync_completed' }).catch(() => {});
            }
        } catch (e) {
            console.warn('[Sync Realtime] Error handling change:', e);
        }
    }

    /**
     * Delete a local IndexedDB item by its uuid.
     */
    async function _deleteLocalItemByUuid(uuid) {
        try {
            const db = await AppDB.initDB();
            const tx = db.transaction([AppDB.ITEMS_STORE], 'readwrite');
            const store = tx.objectStore(AppDB.ITEMS_STORE);
            const idx = store.index('uuid');
            const req = idx.get(uuid);
            req.onsuccess = () => {
                if (req.result) store.delete(req.result.id);
            };
            await new Promise((resolve) => { tx.oncomplete = resolve; tx.onerror = resolve; });
        } catch (e) {
            console.warn('[Sync] _deleteLocalItemByUuid failed:', e);
        }
    }

    /**
     * Delete a local IndexedDB folder by its uuid.
     */
    async function _deleteLocalFolderByUuid(uuid) {
        try {
            const db = await AppDB.initDB();
            const tx = db.transaction([AppDB.FOLDERS_STORE], 'readwrite');
            const store = tx.objectStore(AppDB.FOLDERS_STORE);
            const idx = store.index('uuid');
            const req = idx.get(uuid);
            req.onsuccess = () => {
                if (req.result) store.delete(req.result.id);
            };
            await new Promise((resolve) => { tx.oncomplete = resolve; tx.onerror = resolve; });
        } catch (e) {
            console.warn('[Sync] _deleteLocalFolderByUuid failed:', e);
        }
    }

    // ========================================================================
    // CLOUD UPLOAD / DOWNLOAD HELPERS
    // ========================================================================

    /**
     * Upload all local data to Supabase — per-item upserts.
     */
    async function _uploadAllToCloud(uid, localData) {
        const sb = await _getAuthenticatedClient();
        const now = new Date().toISOString();

        // Upload folders — per-row upsert
        if (localData.folders && localData.folders.length > 0) {
            const folderRows = localData.folders.map(f => ({
                user_id: uid,
                uuid: f.uuid,
                name: f.name,
                pin: f.pin || null,
                parent_id: f.parentId || null,
                order: f.order || 0,
                version: f.version || 1,
                created_at: f.createdAt || now,
                updated_at: f.updatedAt || now
            }));
            const { error } = await sb.from('folders').upsert(folderRows, { onConflict: 'user_id,uuid' });
            if (error) console.error('[Sync] Folder upsert error:', error);
        }

        // Upload notes — per-row upsert
        if (localData.items && localData.items.length > 0) {
            const noteRows = [];
            for (const item of localData.items) {
                let fileUrl = item.fileUrl || null;

                // Upload blob to Supabase Storage if it's a raw Blob
                if (item.fileBlob && item.fileBlob instanceof Blob) {
                    fileUrl = await _uploadBlobToStorage(sb, uid, item.fileBlob, item.uuid);
                }

                // Find the folder uuid from folderId
                let folderUuid = item.folderUuid || null;
                if (!folderUuid && item.folderId && localData.folders) {
                    const folder = localData.folders.find(f => f.id === item.folderId);
                    if (folder) folderUuid = folder.uuid;
                }

                noteRows.push({
                    user_id: uid,
                    uuid: item.uuid,
                    folder_uuid: folderUuid,
                    type: item.type || 'text',
                    title: item.title || null,
                    content: item.content || null,
                    file_url: fileUrl,
                    file_mime_type: item.fileMimeType || item.fileBlob?.type || null,
                    tags: item.tags || [],
                    version: item.version || 1,
                    created_at: item.createdAt || now,
                    updated_at: item.updatedAt || now
                });
            }
            const { error } = await sb.from('notes').upsert(noteRows, { onConflict: 'user_id,uuid' });
            if (error) console.error('[Sync] Notes upsert error:', error);
        }

        // Upload vault data
        if (localData.vault) {
            const vaultPayload = { ...localData.vault };
            delete vaultPayload._updatedAt;

            await sb.from('vault_data').upsert({
                user_id: uid,
                encrypted_vault: vaultPayload,
                version: vaultPayload.version || 1,
                updated_at: now
            }, { onConflict: 'user_id' });
        }

        // Upload vault keys
        if (localData.vaultKeys) {
            await sb.from('vault_keys').upsert({
                user_id: uid,
                salt: localData.vaultKeys.salt,
                edek: localData.vaultKeys.edek,
                edek_iv: localData.vaultKeys.edek_iv,
                validator: localData.vaultKeys.validator,
                validator_iv: localData.vaultKeys.validator_iv
            }, { onConflict: 'user_id' });
        }

        // Upload settings
        if (localData.settings && Object.keys(localData.settings).length > 0) {
            await sb.from('user_settings').upsert({
                user_id: uid,
                settings: localData.settings,
                updated_at: now
            }, { onConflict: 'user_id' });
        }
    }

    /**
     * Download all cloud data and apply locally.
     */
    async function _downloadAllFromCloud(uid) {
        const sb = await _getAuthenticatedClient();

        const { data: cloudNotes } = await sb.from('notes').select('*').eq('user_id', uid);
        const { data: cloudFolders } = await sb.from('folders').select('*').eq('user_id', uid);
        const { data: cloudVault } = await sb.from('vault_data').select('*').eq('user_id', uid).maybeSingle();
        const { data: cloudVaultKeys } = await sb.from('vault_keys').select('*').eq('user_id', uid).maybeSingle();
        const { data: cloudSettings } = await sb.from('user_settings').select('*').eq('user_id', uid).maybeSingle();

        // Convert cloud rows to local format and import
        if (cloudFolders || cloudNotes) {
            const importData = {
                folders: (cloudFolders || []).map(f => ({
                    uuid: f.uuid,
                    name: f.name,
                    pin: f.pin,
                    parentId: f.parent_id,
                    order: f.order,
                    version: f.version,
                    createdAt: f.created_at,
                    updatedAt: f.updated_at
                })),
                items: (cloudNotes || []).map(n => ({
                    uuid: n.uuid,
                    folderUuid: n.folder_uuid,
                    type: n.type,
                    title: n.title,
                    content: n.content,
                    fileUrl: n.file_url,
                    fileMimeType: n.file_mime_type,
                    tags: n.tags,
                    version: n.version,
                    createdAt: n.created_at,
                    updatedAt: n.updated_at
                }))
            };
            await importNotesData(importData);
        }

        if (cloudVault && cloudVault.encrypted_vault) {
            await _importVaultData(cloudVault.encrypted_vault, cloudVault.version);
        }

        if (cloudVaultKeys) {
            await new Promise(r => chrome.storage.local.set({
                pm_vault_keys: {
                    salt: cloudVaultKeys.salt,
                    edek: cloudVaultKeys.edek,
                    edek_iv: cloudVaultKeys.edek_iv,
                    validator: cloudVaultKeys.validator,
                    validator_iv: cloudVaultKeys.validator_iv
                }
            }, r));
        }

        if (cloudSettings && cloudSettings.settings) {
            await _importSettingsData(cloudSettings.settings, cloudSettings.updated_at);
        }

        const state = await _getSyncState();
        state.lastSyncedAt = new Date().toISOString();
        state.syncStatus = 'idle';
        await _setSyncState(state);
    }

    /**
     * Upload a Blob to Supabase Storage.
     */
    async function _uploadBlobToStorage(sb, uid, blob, itemUuid) {
        try {
            const storagePath = `${uid}/${itemUuid || crypto.randomUUID()}`;
            const { error } = await sb.storage.from('user-files').upload(storagePath, blob, {
                contentType: blob.type || 'application/octet-stream',
                upsert: true
            });

            if (error) {
                console.warn('[Sync] Blob upload failed:', error);
                return null;
            }

            const { data: urlData } = sb.storage.from('user-files').getPublicUrl(storagePath);
            return urlData?.publicUrl || null;
        } catch (err) {
            console.warn('[Sync] _uploadBlobToStorage error:', err);
            return null;
        }
    }

    /**
     * Merge local and cloud notes data.
     * Deduplicates by `uuid`. Higher `version` wins. Timestamp tiebreaker.
     * Tombstoned items are excluded.
     */
    function _mergeNotesData(localData, cloudData, tombstones) {
        let localWon = false;

        // Map of uuid -> max tombstone version
        const tombstoneMap = new Map();
        if (tombstones && tombstones.items) {
            for (const t of tombstones.items) {
                const currentMax = tombstoneMap.get(t.uuid) || 0;
                const tVer = t.version || 999999;
                if (tVer > currentMax) tombstoneMap.set(t.uuid, tVer);
            }
        }

        function isTombstoned(itemOrFolder) {
            const key = itemOrFolder.uuid || String(itemOrFolder.id);
            const tombstoneVersion = tombstoneMap.get(key);
            if (tombstoneVersion === undefined) return false;
            const itemVer = itemOrFolder.version || 1;
            return tombstoneVersion > itemVer;
        }

        // ── FOLDERS ───────────────────────────────────────────────────────────
        const folderMap = new Map();

        if (cloudData && cloudData.folders) {
            for (const f of cloudData.folders) {
                const key = f.uuid || String(f.id);
                if (!isTombstoned(f)) folderMap.set(key, f);
            }
        }
        if (localData && localData.folders) {
            for (const f of localData.folders) {
                const key = f.uuid || String(f.id);
                if (isTombstoned(f)) continue;

                if (!folderMap.has(key)) {
                    folderMap.set(key, f);
                    localWon = true;
                } else {
                    const existing = folderMap.get(key);
                    const localVer = f.version || 1;
                    const cloudVer = existing.version || 1;

                    if (localVer > cloudVer) {
                        folderMap.set(key, f);
                        localWon = true;
                    } else if (localVer === cloudVer) {
                        const existingTime = new Date(existing.updatedAt || existing.updated_at || existing.createdAt || existing.created_at || 0).getTime();
                        const localTime = new Date(f.updatedAt || f.createdAt || 0).getTime();
                        if (localTime > existingTime) {
                            folderMap.set(key, f);
                            localWon = true;
                        }
                    }
                }
            }
        }

        // ── ITEMS ─────────────────────────────────────────────────────────────
        const itemMap = new Map();

        if (cloudData && cloudData.items) {
            for (const item of cloudData.items) {
                const key = item.uuid || String(item.id);
                if (!isTombstoned(item)) itemMap.set(key, item);
            }
        }
        if (localData && localData.items) {
            for (const item of localData.items) {
                const key = item.uuid || String(item.id);
                if (isTombstoned(item)) continue;

                if (!itemMap.has(key)) {
                    itemMap.set(key, item);
                    localWon = true;
                } else {
                    const existing = itemMap.get(key);
                    const localVer = item.version || 1;
                    const cloudVer = existing.version || 1;

                    if (localVer > cloudVer) {
                        itemMap.set(key, item);
                        localWon = true;
                    } else if (localVer === cloudVer) {
                        const existingTime = new Date(existing.updatedAt || existing.updated_at || existing.createdAt || existing.created_at || 0).getTime();
                        const localTime = new Date(item.updatedAt || item.createdAt || 0).getTime();
                        if (localTime > existingTime) {
                            itemMap.set(key, item);
                            localWon = true;
                        }
                    }
                }
            }
        }

        return {
            data: {
                folders: Array.from(folderMap.values()),
                items: Array.from(itemMap.values())
            },
            localWon
        };
    }

    /**
     * Physically delete items from local IndexedDB that match valid tombstones.
     */
    async function _applyTombstonesLocally(tombstones, localData) {
        if (!tombstones || !tombstones.items || tombstones.items.length === 0) return;
        if (!localData) return;

        const tombstoneMap = new Map();
        for (const t of tombstones.items) {
            const currentMax = tombstoneMap.get(t.uuid) || 0;
            const tVer = t.version || 999999;
            if (tVer > currentMax) tombstoneMap.set(t.uuid, tVer);
        }

        function isTombstoned(itemOrFolder) {
            const key = itemOrFolder.uuid || String(itemOrFolder.id);
            const tombstoneVersion = tombstoneMap.get(key);
            if (tombstoneVersion === undefined) return false;
            return tombstoneVersion > (itemOrFolder.version || 1);
        }

        const idsToDeleteItems = (localData.items || []).filter(i => isTombstoned(i)).map(i => i.id);
        const idsToDeleteFolders = (localData.folders || []).filter(f => isTombstoned(f)).map(f => f.id);

        if (idsToDeleteItems.length === 0 && idsToDeleteFolders.length === 0) return;

        const db = await AppDB.initDB();

        if (idsToDeleteItems.length > 0) {
            await new Promise(resolve => {
                const tx = db.transaction([AppDB.ITEMS_STORE], 'readwrite');
                const store = tx.objectStore(AppDB.ITEMS_STORE);
                idsToDeleteItems.forEach(id => store.delete(id));
                tx.oncomplete = resolve;
                tx.onerror = resolve;
            });
        }

        if (idsToDeleteFolders.length > 0) {
            await new Promise(resolve => {
                const tx = db.transaction([AppDB.FOLDERS_STORE], 'readwrite');
                const store = tx.objectStore(AppDB.FOLDERS_STORE);
                idsToDeleteFolders.forEach(id => store.delete(id));
                tx.oncomplete = resolve;
                tx.onerror = resolve;
            });
        }
    }

    // ========================================================================
    // DATA EXPORT / IMPORT
    // ========================================================================

    /**
     * Export all local data into a JSON-serializable object.
     */
    async function exportLocalData() {
        const db = await AppDB.initDB();
        const folders = await AppDB.getAllFolders();
        const items = await AppDB.getAllItems();

        // Vault data from chrome.storage
        const vaultData = await new Promise(resolve => {
            chrome.storage.local.get(['pm_vault_data', 'pm_vault_keys', 'vault_tombstones', 'vault_updatedAt'], resolve);
        });

        // Settings
        const settingsData = await new Promise(resolve => {
            chrome.storage.local.get(['pm_settings', 'settings_updatedAt'], resolve);
        });

        return {
            folders,
            items,
            vault: vaultData.pm_vault_data,
            vaultKeys: vaultData.pm_vault_keys,
            vaultTombstones: vaultData.vault_tombstones,
            settings: settingsData.pm_settings || {},
            _settingsUpdatedAt: settingsData.settings_updatedAt || null
        };
    }

    /**
     * Import (upsert) notes data into IndexedDB.
     * Uses put() per item matched by uuid — NEVER clears the store.
     */
    async function importNotesData(data) {
        if (!data || !data.folders || !data.items) return;
        const db = await AppDB.initDB();

        // ── Upsert folders ────────────────────────────────────────────────────
        await new Promise((resolve, reject) => {
            const tx = db.transaction([AppDB.FOLDERS_STORE], 'readwrite');
            const store = tx.objectStore(AppDB.FOLDERS_STORE);

            let pending = data.folders.length;
            if (pending === 0) { tx.oncomplete = resolve; return; }

            for (const folder of data.folders) {
                const { id: _dropped, ...rest } = folder;

                if (rest.uuid) {
                    const req = store.index('uuid').get(rest.uuid);
                    req.onsuccess = () => {
                        if (req.result) {
                            store.put({ ...req.result, ...rest });
                        } else {
                            store.add(rest);
                        }
                        if (--pending === 0) { /* wait for oncomplete */ }
                    };
                } else {
                    store.put({ ...rest, id: _dropped });
                }
            }

            tx.oncomplete = resolve;
            tx.onerror = reject;
        });

        // ── Upsert items ──────────────────────────────────────────────────────
        await new Promise((resolve, reject) => {
            const tx = db.transaction([AppDB.ITEMS_STORE], 'readwrite');
            const store = tx.objectStore(AppDB.ITEMS_STORE);

            let pending = data.items.length;
            if (pending === 0) { tx.oncomplete = resolve; return; }

            for (const item of data.items) {
                const copy = { ...item };

                // Legacy support for base64
                if (copy._hasBlobData && typeof copy.fileBlob === 'string') {
                    delete copy.fileBlob;
                    delete copy._hasBlobData;
                }

                const { id: _dropped, ...rest } = copy;

                if (rest.uuid) {
                    const req = store.index('uuid').get(rest.uuid);
                    req.onsuccess = () => {
                        if (req.result) {
                            store.put({ ...req.result, ...rest });
                        } else {
                            store.add(rest);
                        }
                        if (--pending === 0) { /* wait for oncomplete */ }
                    };
                } else {
                    store.put({ ...rest, id: _dropped });
                }
            }

            tx.oncomplete = resolve;
            tx.onerror = reject;
        });
    }

    async function _importVaultData(vaultPayload, version) {
        if (!vaultPayload) return;
        const payload = { ...vaultPayload };
        if (version) payload.version = version;

        await new Promise(resolve => {
            chrome.storage.local.set({
                pm_vault_data: payload,
                vault_updatedAt: new Date().toISOString()
            }, resolve);
        });
    }

    async function _importSettingsData(settingsPayload, updatedAt) {
        if (!settingsPayload) return;
        await new Promise(resolve => {
            chrome.storage.local.set({
                pm_settings: settingsPayload,
                settings_updatedAt: updatedAt || new Date().toISOString()
            }, resolve);
        });
    }

    // ========================================================================
    // USER REGISTRY
    // ========================================================================

    async function _registerUser(profile) {
        const sb = await _getAuthenticatedClient();
        const uid = profile.uid;

        const { data: existing } = await sb.from('profiles').select('*').eq('id', uid).maybeSingle();

        if (existing) {
            await sb.from('profiles').update({
                name: profile.name,
                avatar_url: profile.avatarUrl,
                last_synced_at: new Date().toISOString(),
                extension_version: chrome.runtime.getManifest().version
            }).eq('id', uid);

            // Sync premium status from server
            const state = await _getSyncState();
            state.isPremium = existing.is_premium || false;
            await _setSyncState(state);
        } else {
            await sb.from('profiles').insert({
                id: uid,
                email: profile.email,
                name: profile.name,
                avatar_url: profile.avatarUrl,
                provider: profile.provider || 'unknown',
                is_premium: false,
                premium_since: null,
                registered_at: new Date().toISOString(),
                last_synced_at: new Date().toISOString(),
                extension_version: chrome.runtime.getManifest().version
            });
        }
    }

    /**
     * Fetch all users from profiles table (admin only).
     */
    async function fetchAllUsers() {
        const sb = await _getAuthenticatedClient();

        const { data, error } = await sb.from('profiles').select('*').order('registered_at', { ascending: false }).limit(1000);

        if (error) throw error;
        if (!data) return [];

        // Map to the format admin.js expects
        return data.map(u => ({
            uid: u.id,
            email: u.email,
            name: u.name,
            avatarUrl: u.avatar_url,
            isPremium: u.is_premium,
            premiumSince: u.premium_since,
            registeredAt: u.registered_at,
            lastSyncedAt: u.last_synced_at,
            extensionVersion: u.extension_version
        }));
    }

    /**
     * Update a user's profile (admin function).
     */
    async function updateUserProfile(uid, updates) {
        const sb = await _getAuthenticatedClient();
        const { error } = await sb.from('profiles').update(updates).eq('id', uid);
        if (error) throw error;
    }

    // ========================================================================
    // HELPERS
    // ========================================================================

    function _getSyncState() {
        return new Promise(resolve => {
            chrome.storage.local.get([SYNC_STATE_KEY], (result) => {
                resolve(result[SYNC_STATE_KEY] || {
                    lastSyncedAt: null,
                    googleProfile: null,
                    accessToken: null,
                    refreshToken: null,
                    isPremium: false,
                    autoSync: true,
                    syncStatus: 'idle',
                    tokenExpiresAt: null
                });
            });
        });
    }

    function _setSyncState(state) {
        return new Promise(resolve => {
            chrome.storage.local.set({ [SYNC_STATE_KEY]: state }, resolve);
        });
    }

    // ========================================================================
    // TIME HELPERS
    // ========================================================================

    function getRelativeTime(isoString) {
        if (!isoString) return 'Never';
        const diff = Date.now() - new Date(isoString).getTime();
        const seconds = Math.floor(diff / 1000);
        if (seconds < 60) return 'Just now';
        const minutes = Math.floor(seconds / 60);
        if (minutes < 60) return `${minutes} min ago`;
        const hours = Math.floor(minutes / 60);
        if (hours < 24) return `${hours}h ago`;
        const days = Math.floor(hours / 24);
        return `${days}d ago`;
    }

    // ========================================================================
    // PUBLIC API
    // ========================================================================

    return {
        // Auth
        signIn,
        signOut,
        isSignedIn,
        getProfile,
        isAdmin,
        handleAuthResult,

        // Premium
        isPremium,
        setPremiumStatus,

        // Sync
        syncAll,
        triggerAutoSync,
        exportLocalData,
        importNotesData,
        handleMergeResponse,

        // Admin
        fetchAllUsers,
        updateUserProfile,
        ADMIN_EMAILS,

        // Helpers
        getRelativeTime,

        // Internal (for admin.js and background.js)
        _getAuthenticatedClient,
        _getSyncState,
        _recordTombstone
    };

})();

globalThis.SyncService = SyncService;
